In [ ]:
import pandas as pd
# Upload file
from google.colab import files
uploaded = files.upload()
# File name
file_name = "Sales_Data_txt.txt"
# Read file line by line
with open("Sales_Data_txt.txt") as f:
    lines = f.read().splitlines()

# First line = header
cols = lines[0].split()
# Data : Fix rows with extra values
rows = []
for line in lines[1:]:
    values = line.split()
    if len(values) > len(cols):
        values = values[:3] + [" ".join(values[3:-23])] + values[-23:]
    rows.append(values)

# Create DataFrame
df = pd.DataFrame(rows, columns=cols)
# Convert to CSV
df.to_csv("Sales_Dataset.csv", index=False)

Saving Sales_Data_txt.txt to Sales_Data_txt (2).txt

In [ ]:
# Download CSV file
files.download("Sales_Dataset.csv")

In [ ]:
# Load the dataset
from google.colab import files
uploaded = files.upload()
# Function to load CSV file using Pandas
import pandas as pd
dataset = pd.read_csv('Sales_Dataset.csv')
dataset.head()

Saving Sales_Dataset.csv to Sales_Dataset (3).csv

,OrderID,OrderDate,CustomerName,Product,Quantity,UnitPrice,TotalAmount,Region,Salesperson,Country,...,Tax,OrderStatus,PaymentMode,ShipmentDate,DeliveryDate,ShippingPartner,DeliveryDays,CustomerType,CustomerRating,CustomerSince
0,5001,01/03/24,ShreeSales,Keyboard-USB,6,NaN,2550.0,NaN,NaN,UAE,...,12,Completed,Card,2024-03-01,2024-01-13,NaN,10,Wholesale,5,2022
1,5002,01/03/24,Shree_Sales,Laptop-15,3,55000.0,2550.0,NaN,Rohann,USA,...,18,Pending,Card,2024-03-01,2024/02/17,BlueDart,6,Wholesale,5,2019
2,5003,2024-03-01,AmarTraders,Monitor24,2,450.0,110000.0,NaN,NaN,NaN,...,18,Completed,UPI,2024-01-13,2024-03-01,NaN,1,Wholesale,4,2022
3,5004,15/02/24,Amar_Traders,KeyboardUSB,5,NaN,24000.0,East,NaN,USA,...,5,Pending,UPI,13-01-2024,15/02/24,DHL,6,Retail,1,2019
4,5005,15/02/24,Amar_Traders,Laptop_15,1,850.0,2550.0,West,Rina,UAE,...,12,Pending,UPI,2024-01-13,2024-03-01,DHL,5,Wholesale,1,2022

In [ ]:
# Data Preprocessing
# Read CSV file
df = pd.read_csv("Sales_Dataset.csv")

# Check basic info
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          10000 non-null  int64
 1   OrderDate        10000 non-null  object
 2   CustomerName     8925 non-null   object
 3   Product          10000 non-null  object
 4   Quantity         10000 non-null  int64
 5   UnitPrice        7999 non-null   float64
 6   TotalAmount      8002 non-null   float64
 7   Region           8031 non-null   object
 8   Salesperson      7999 non-null   object
 9   Country          8376 non-null   object
 10  State            8374 non-null   object
 11  City             8305 non-null   object
 12  Category         10000 non-null  object
 13  SubCategory      7959 non-null   object
 14  Brand            8335 non-null   object
 15  CostPrice        8045 non-null   float64
 16  Discount         10000 non-null  int64
 17  Tax              10000 non-null  int64
 18  OrderStatus      10000 non-null  object
 19  PaymentMode      10000 non-null  object
 20  ShipmentDate     10000 non-null  object
 21  DeliveryDate     10000 non-null  object
 22  ShippingPartner  7911 non-null   object
 23  DeliveryDays     10000 non-null  int64
 24  CustomerType     10000 non-null  object
 25  CustomerRating   10000 non-null  int64
 26  CustomerSince    10000 non-null  int64
dtypes: float64(3), int64(7), object(17)
memory usage: 2.1+ MB
None

In [ ]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Date columns
date_cols = ["OrderDate", "ShipmentDate", "DeliveryDate"]
# Convert & format dates
for col in date_cols:
    # First attempt (general parsing)
    parsed = pd.to_datetime(df[col], errors="coerce", dayfirst=True)
    # Second attempt for still-missing values
    parsed2 = pd.to_datetime(
        df[col],
        errors="coerce",
        format="mixed"
    )
    # Combine both
    df[col] = parsed.fillna(parsed2)
    # Final format
    df[col] = df[col].dt.strftime("%d-%m-%Y")

# Fill missing values with "NA"
df = df.fillna("NA")
df

/tmp/ipython-input-3309971129.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  parsed = pd.to_datetime(df[col], errors="coerce", dayfirst=True)
/tmp/ipython-input-3309971129.py:9: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  parsed = pd.to_datetime(df[col], errors="coerce", dayfirst=True)

,OrderID,OrderDate,CustomerName,Product,Quantity,UnitPrice,TotalAmount,Region,Salesperson,Country,...,Tax,OrderStatus,PaymentMode,ShipmentDate,DeliveryDate,ShippingPartner,DeliveryDays,CustomerType,CustomerRating,CustomerSince
0,5001,01-03-2024,ShreeSales,Keyboard-USB,6,NA,2550.0,NA,NA,UAE,...,12,Completed,Card,03-01-2024,13-01-2024,NA,10,Wholesale,5,2022
1,5002,01-03-2024,Shree_Sales,Laptop-15,3,55000.0,2550.0,NA,Rohann,USA,...,18,Pending,Card,03-01-2024,17-02-2024,BlueDart,6,Wholesale,5,2019
2,5003,01-03-2024,AmarTraders,Monitor24,2,450.0,110000.0,NA,NA,NA,...,18,Completed,UPI,13-01-2024,01-03-2024,NA,1,Wholesale,4,2022
3,5004,15-02-2024,Amar_Traders,KeyboardUSB,5,NA,24000.0,East,NA,USA,...,5,Pending,UPI,13-01-2024,15-02-2024,DHL,6,Retail,1,2019
4,5005,15-02-2024,Amar_Traders,Laptop_15,1,850.0,2550.0,West,Rina,UAE,...,12,Pending,UPI,13-01-2024,01-03-2024,DHL,5,Wholesale,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,14996,13-01-2024,Amar_Traders,Mouse-Wireless,1,NA,110000.0,North,NA,NA,...,12,Cancelled,Card,13-01-2024,01-03-2024,BlueDart,4,Corporate,3,2022
9996,14997,01-03-2024,StarInfoTech,Monitor_24,2,55000.0,NA,NA,NA,UAE,...,18,Cancelled,UPI,03-01-2024,13-01-2024,NA,4,Corporate,3,2022
9997,14998,01-03-2024,StarInfoTech,Monitor_24,4,12000.0,110000.0,West,Rohan,NA,...,12,Cancelled,UPI,13-01-2024,13-01-2024,NA,8,Retail,2,2022
9998,14999,12-01-2024,NA,Mouse-Wireless,6,12000.0,55000.0,West,Rohann,UK,...,5,Completed,Credit,17-02-2024,17-02-2024,Delhivery,9,Retail,3,2019
9999,15000,13-01-2024,Star_Infotech,MouseWireless,4,NA,2550.0,West,Rina,UAE,...,12,Cancelled,UPI,15-02-2024,13-01-2024,NA,1,Wholesale,5,2019

In [ ]:
# Product Cleaning
df["Product"] = (
    df["Product"]
    .str.lower()
    .str.replace("-", " ", regex=False)
    .str.replace("_", " ", regex=False)
    # add space between letters and numbers
    .str.replace(r"([a-zA-Z])(\d)", r"\1 \2", regex=True)
    # add space between words like mousewireless
    .str.replace(r"(mouse)(wireless)", r"\1 \2", regex=True)
    .str.strip()
    .str.title()
)

df["CustomerName"] = (
    df["CustomerName"]
    .astype(str)
    .str.replace("_", " ", regex=False) # underscores → space
    .str.replace("-", " ", regex=False) # hyphens → space
    # add space between letters & numbers
    .str.replace(r"([a-zA-Z])(\d)", r"\1 \2", regex=True)
    # split CamelCase words
    .str.replace(r"([a-z])([A-Z])", r"\1 \2", regex=True)
    # normalize multiple spaces
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.title()
)

# Use a generic suffix-based standardization
import re
def clean_customer_name(name):
    name = str(name).lower()
    # replace separators
    name = name.replace("_", " ").replace("-", " ")
    # split camel case
    name = re.sub(r"([a-z])([A-Z])", r"\1 \2", name)
    # normalize multiple spaces
    name = re.sub(r"\s+", " ", name).strip()
    # merge common business compounds
    name = re.sub(r"\binfo\s+tech\b", "infotech", name)
    name = re.sub(r"\btech\s+solutions\b", "techsolutions", name)
    return name.title()
df["CustomerName"] = df["CustomerName"].apply(clean_customer_name)
df

import re
def clean_product(product):
    p = str(product).strip()
    # Replace separators
    p = re.sub(r"[_\-]", " ", p)
    # Split CamelCase
    p = re.sub(r"([a-z])([A-Z])", r"\1 \2", p)
    # Split letters & numbers
    p = re.sub(r"([A-Za-z])(\d)", r"\1 \2", p)
    p = re.sub(r"(\d)([A-Za-z])", r"\1 \2", p)
    # Normalize
    p = p.lower()
    # Common tech suffix separation (GENERAL, extensible)
    p = re.sub(r"(usb|ssd|hdd|ram|gb|tb|inch|in)", r" \1", p)
    # Clean spaces
    p = re.sub(r"\s+", " ", p).strip()
    return p.title()
df["Product"] = df["Product"].apply(clean_product)
df

,OrderID,OrderDate,CustomerName,Product,Quantity,UnitPrice,TotalAmount,Region,Salesperson,Country,...,Tax,OrderStatus,PaymentMode,ShipmentDate,DeliveryDate,ShippingPartner,DeliveryDays,CustomerType,CustomerRating,CustomerSince
0,5001,01-03-2024,Shree Sales,Keyboard Usb,6,NA,2550.0,NA,NA,UAE,...,12,Completed,Card,03-01-2024,13-01-2024,NA,10,Wholesale,5,2022
1,5002,01-03-2024,Shree Sales,Laptop 15,3,55000.0,2550.0,NA,Rohann,USA,...,18,Pending,Card,03-01-2024,17-02-2024,BlueDart,6,Wholesale,5,2019
2,5003,01-03-2024,Amar Traders,Monitor 24,2,450.0,110000.0,NA,NA,NA,...,18,Completed,UPI,13-01-2024,01-03-2024,NA,1,Wholesale,4,2022
3,5004,15-02-2024,Amar Traders,Keyboard Usb,5,NA,24000.0,East,NA,USA,...,5,Pending,UPI,13-01-2024,15-02-2024,DHL,6,Retail,1,2019
4,5005,15-02-2024,Amar Traders,Laptop 15,1,850.0,2550.0,West,Rina,UAE,...,12,Pending,UPI,13-01-2024,01-03-2024,DHL,5,Wholesale,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,14996,13-01-2024,Amar Traders,Mouse Wireless,1,NA,110000.0,North,NA,NA,...,12,Cancelled,Card,13-01-2024,01-03-2024,BlueDart,4,Corporate,3,2022
9996,14997,01-03-2024,Star Infotech,Monitor 24,2,55000.0,NA,NA,NA,UAE,...,18,Cancelled,UPI,03-01-2024,13-01-2024,NA,4,Corporate,3,2022
9997,14998,01-03-2024,Star Infotech,Monitor 24,4,12000.0,110000.0,West,Rohan,NA,...,12,Cancelled,UPI,13-01-2024,13-01-2024,NA,8,Retail,2,2022
9998,14999,12-01-2024,Na,Mouse Wireless,6,12000.0,55000.0,West,Rohann,UK,...,5,Completed,Credit,17-02-2024,17-02-2024,Delhivery,9,Retail,3,2019
9999,15000,13-01-2024,Star Infotech,Mouse Wireless,4,NA,2550.0,West,Rina,UAE,...,12,Cancelled,UPI,15-02-2024,13-01-2024,NA,1,Wholesale,5,2019

Warning: Total number of columns (27) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
# Calculate mean excluding zeros and round to 1 decimal
qty_mean = round(df.loc[df["Quantity"] != 0, "Quantity"].mean(), 1)
# # Fill quantity=0 with mean
df["Quantity"] = df["Quantity"].replace(0, qty_mean)
df

,OrderID,OrderDate,CustomerName,Product,Quantity,UnitPrice,TotalAmount,Region,Salesperson,Country,...,Tax,OrderStatus,PaymentMode,ShipmentDate,DeliveryDate,ShippingPartner,DeliveryDays,CustomerType,CustomerRating,CustomerSince
0,5001,01-03-2024,Shree Sales,Keyboard Usb,6.0,NA,2550.0,NA,NA,UAE,...,12,Completed,Card,03-01-2024,13-01-2024,NA,10,Wholesale,5,2022
1,5002,01-03-2024,Shree Sales,Laptop 15,3.0,55000.0,2550.0,NA,Rohann,USA,...,18,Pending,Card,03-01-2024,17-02-2024,BlueDart,6,Wholesale,5,2019
2,5003,01-03-2024,Amar Traders,Monitor 24,2.0,450.0,110000.0,NA,NA,NA,...,18,Completed,UPI,13-01-2024,01-03-2024,NA,1,Wholesale,4,2022
3,5004,15-02-2024,Amar Traders,Keyboard Usb,5.0,NA,24000.0,East,NA,USA,...,5,Pending,UPI,13-01-2024,15-02-2024,DHL,6,Retail,1,2019
4,5005,15-02-2024,Amar Traders,Laptop 15,1.0,850.0,2550.0,West,Rina,UAE,...,12,Pending,UPI,13-01-2024,01-03-2024,DHL,5,Wholesale,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,14996,13-01-2024,Amar Traders,Mouse Wireless,1.0,NA,110000.0,North,NA,NA,...,12,Cancelled,Card,13-01-2024,01-03-2024,BlueDart,4,Corporate,3,2022
9996,14997,01-03-2024,Star Infotech,Monitor 24,2.0,55000.0,NA,NA,NA,UAE,...,18,Cancelled,UPI,03-01-2024,13-01-2024,NA,4,Corporate,3,2022
9997,14998,01-03-2024,Star Infotech,Monitor 24,4.0,12000.0,110000.0,West,Rohan,NA,...,12,Cancelled,UPI,13-01-2024,13-01-2024,NA,8,Retail,2,2022
9998,14999,12-01-2024,Na,Mouse Wireless,6.0,12000.0,55000.0,West,Rohann,UK,...,5,Completed,Credit,17-02-2024,17-02-2024,Delhivery,9,Retail,3,2019
9999,15000,13-01-2024,Star Infotech,Mouse Wireless,4.0,NA,2550.0,West,Rina,UAE,...,12,Cancelled,UPI,15-02-2024,13-01-2024,NA,1,Wholesale,5,2019

Warning: Total number of columns (27) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
# Convert 'UnitPrice' to numeric, coercing 'NA' to NaN
df["UnitPrice"] = pd.to_numeric(df["UnitPrice"], errors='coerce')
# Fill missing UnitPrice with median
df["UnitPrice"].fillna(df["UnitPrice"].median(), inplace=True)
df

/tmp/ipython-input-970731761.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["UnitPrice"].fillna(df["UnitPrice"].median(), inplace=True)

,OrderID,OrderDate,CustomerName,Product,Quantity,UnitPrice,TotalAmount,Region,Salesperson,Country,...,Tax,OrderStatus,PaymentMode,ShipmentDate,DeliveryDate,ShippingPartner,DeliveryDays,CustomerType,CustomerRating,CustomerSince
0,5001,01-03-2024,Shree Sales,Keyboard Usb,6.0,850.0,2550.0,NA,NA,UAE,...,12,Completed,Card,03-01-2024,13-01-2024,NA,10,Wholesale,5,2022
1,5002,01-03-2024,Shree Sales,Laptop 15,3.0,55000.0,2550.0,NA,Rohann,USA,...,18,Pending,Card,03-01-2024,17-02-2024,BlueDart,6,Wholesale,5,2019
2,5003,01-03-2024,Amar Traders,Monitor 24,2.0,450.0,110000.0,NA,NA,NA,...,18,Completed,UPI,13-01-2024,01-03-2024,NA,1,Wholesale,4,2022
3,5004,15-02-2024,Amar Traders,Keyboard Usb,5.0,850.0,24000.0,East,NA,USA,...,5,Pending,UPI,13-01-2024,15-02-2024,DHL,6,Retail,1,2019
4,5005,15-02-2024,Amar Traders,Laptop 15,1.0,850.0,2550.0,West,Rina,UAE,...,12,Pending,UPI,13-01-2024,01-03-2024,DHL,5,Wholesale,1,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,14996,13-01-2024,Amar Traders,Mouse Wireless,1.0,850.0,110000.0,North,NA,NA,...,12,Cancelled,Card,13-01-2024,01-03-2024,BlueDart,4,Corporate,3,2022
9996,14997,01-03-2024,Star Infotech,Monitor 24,2.0,55000.0,NA,NA,NA,UAE,...,18,Cancelled,UPI,03-01-2024,13-01-2024,NA,4,Corporate,3,2022
9997,14998,01-03-2024,Star Infotech,Monitor 24,4.0,12000.0,110000.0,West,Rohan,NA,...,12,Cancelled,UPI,13-01-2024,13-01-2024,NA,8,Retail,2,2022
9998,14999,12-01-2024,Na,Mouse Wireless,6.0,12000.0,55000.0,West,Rohann,UK,...,5,Completed,Credit,17-02-2024,17-02-2024,Delhivery,9,Retail,3,2019
9999,15000,13-01-2024,Star Infotech,Mouse Wireless,4.0,850.0,2550.0,West,Rina,UAE,...,12,Cancelled,UPI,15-02-2024,13-01-2024,NA,1,Wholesale,5,2019

Warning: Total number of columns (27) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
# Save preprocessed file
df.to_csv("Preprocessed_Sales_Dataset.csv", index=False)
# Download preprocessed file
files.download("Preprocessed_Sales_Dataset.csv")